// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RunsColumns holds the columns for the "runs" table.
	RunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "job", Type: field.TypeString},
		{Name: "start", Type: field.TypeTime, Nullable: true},
		{Name: "end", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"running", "failed", "successful"}},
		{Name: "log", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// RunsTable holds the schema information for the "runs" table.
	RunsTable = &schema.Table{
		Name:       "runs",
		Columns:    RunsColumns,
		PrimaryKey: []*schema.Column{RunsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RunsTable,
	}
)

func init() {
}
